logLevel = "debug"
[install]
# whether to install optionalDependencies
optional = true

# whether to install devDependencies
dev = true

# whether to install peerDependencies
peer = true

[debug]
editor = "code"

[bundle]
entryPoints = ["./src/index.tsx"]
